name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

  
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: Compile assets
        run: |
          npm install --package-lock-only
          npm ci
          npm run build

      - name: Deploy to Ubuntu server
        run: |
          rsync -avz --delete-after --exclude=".env" --exclude="vendor/" --exclude="node_modules/" ./ ubuntu@52.66.185.181:/var/www/html

      - name: Disable host key verification
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.66.185.181 "echo Host key verification disabled"

      - name: Run Laravel migrations
        run: |
          ssh ubuntu@52.66.185.181 "cd /var/www/html && php artisan migrate --force"
