name: Deploy to Remote Server

on:
  push:
    branches:
      - master

env:
  REMOTE_HOST: 52.66.185.181
  REMOTE_USER: ubuntu
  REMOTE_PORT: 22
  REMOTE_DIRECTORY: /var/www/html

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Generate assets
        run: |
          npm install --package-lock-only
          npm ci
          npm run build
          
#       - name: deploy
#         uses: up9cloud/action-rsync@master
#         env:
#           HOST: 52.66.185.181
#           KEY: ${{secrets.SSH_PRIVATE_KEY}}
#           TARGET: /var/www/html
      - name: Clear known hosts
        run: ssh-keygen -R your-server-ip

      - name: Deploy to remote server
        run: |
          rsync -azP --delete -e "ssh -p ${{ env.REMOTE_PORT }}" \
            --exclude='.git*' --exclude='vendor/' --exclude='node_modules/' \
            ./ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.REMOTE_DIRECTORY }}

          ssh -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "cd ${{ env.REMOTE_DIRECTORY }} && \
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && \
            php artisan migrate --force && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan optimize"
  
