name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Deploy to EC2
        run: |
          aws configure set aws_access_key_id AKIA5I76TBNTHW4Z5TV5
          aws configure set aws_secret_access_key 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
          aws configure set default.region ap-south-1

          scp -r -i C:\Users\havis\Downloads\Fial.pem ./ ubuntu@3.108.54.189:~/app
          ssh -i C:\Users\havis\Downloads\Fial.pem ubuntu@3.108.54.189 'cd ~/app && composer install --no-dev --optimize-autoloader && php artisan migrate --seed'

      - name: Slack Send Message
        uses: linkinn/slack-msg-action@v1.2.0
        with:
          channel: 'C05A532SBMM'
          message: |
            The deployment of the Laravel application to EC2 is successful!
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
