name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync -y

      - name: Deploy to EC2
        run: |
          ssh-keyscan -H 52.66.185.181 >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" --exclude='.git*' --exclude='vendor/' . ${{ secrets.SSH_USERNAME }}@52.66.185.181:/var/www/html/
