name: Deploy to EC2

on:
  push:
    branches:
      - master

env:
  REMOTE_HOST: 52.66.185.181
  REMOTE_USER: ubuntu
  REMOTE_PORT: 22
  REMOTE_DIRECTORY: /path/to/remote/directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Build assets
        run: npm ci && npm run production

      - name: Deploy to remote server
        run: |
          rsync -azP --delete -e "ssh -p ${{ env.REMOTE_PORT }}" \
            --exclude-from=rsync-exclude.txt ./ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.REMOTE_DIRECTORY }}
          ssh -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "cd ${{ env.REMOTE_DIRECTORY }} && \
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && \
            php artisan migrate --force && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan optimize"
