name: Notify Slack

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Message
        uses: actions/checkout@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            Deployment successful!
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
            Committer: ${{ github.actor }}
          SLACK_CHANNEL: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
